# SQL Server Configuration

SERVER = r"DESKTOP-A0I0PG7\SQLEXPRESS"

DATABASE = "EnterpriseSalesDB"

DRIVER = "ODBC Driver 18 for SQL Server"

TRUSTED_CONNECTION = "yes"

TRUST_SERVER_CERTIFICATE = "yes"