import pandas as pd
import plotly.express as px

def customer_chart_layout(fig):

    fig.update_layout(
        template="plotly_white",
        height=420,
        margin=dict(
            l=40,
            r=40,
            t=70,
            b=40
        ),
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1
        )
    )

    return fig
# ==========================================================
# CUSTOMER KPI ENGINE
# ==========================================================

def total_customers(df):
    """Return the number of unique customers."""

    return df["Customer ID"].nunique()


def total_customer_revenue(df):
    """Return total revenue generated by customers."""

    return df["Revenue"].sum()


def total_customer_profit(df):
    """Return total profit generated by customers."""

    return df["Profit"].sum()


def average_customer_revenue(df):
    """Return average revenue per unique customer."""

    customers = df["Customer ID"].nunique()

    if customers == 0:
        return 0

    return df["Revenue"].sum() / customers


def average_customer_profit(df):
    """Return average profit per unique customer."""

    customers = df["Customer ID"].nunique()

    if customers == 0:
        return 0

    return df["Profit"].sum() / customers


def customer_orders(df):
    """Return total number of customer transactions."""

    return len(df)


def customer_purchase_frequency(df):
    """Return average number of transactions per customer."""

    customers = df["Customer ID"].nunique()

    if customers == 0:
        return 0

    return len(df) / customers


def customer_profit_margin(df):
    """Return overall customer profit margin."""

    revenue = df["Revenue"].sum()

    if revenue == 0:
        return 0

    return df["Profit"].sum() / revenue

# ==========================================================
# NEW VS RETURNING CUSTOMERS
# ==========================================================

def new_customers(df):

    customer_orders = (
        df.groupby("Customer ID")
        .agg(
            FirstPurchase=("Order Date", "min"),
            Orders=("Order ID", "nunique"),
        )
        .reset_index()
    )

    return (
        customer_orders["Orders"] == 1
    ).sum()


def returning_customers(df):

    customer_orders = (
        df.groupby("Customer ID")
        .agg(
            Orders=("Order ID", "nunique"),
        )
        .reset_index()
    )

    return (
        customer_orders["Orders"] > 1
    ).sum()


def repeat_customer_rate(df):

    customers = df["Customer ID"].nunique()

    if customers == 0:
        return 0

    returning = returning_customers(df)

    return returning / customers * 100

# ==========================================================
# NEW VS RETURNING CUSTOMERS
# ==========================================================

def new_vs_returning_customers_chart(df):

    customer_orders = (
        df.groupby("Customer ID")
        .agg(
            Orders=("Order ID", "nunique")
        )
        .reset_index()
    )

    customer_orders["Customer Type"] = (
        customer_orders["Orders"]
        .apply(
            lambda x:
            "New Customer"
            if x == 1
            else "Returning Customer"
        )
    )

    summary = (
        customer_orders
        .groupby(
            "Customer Type",
            as_index=False
        )
        .agg(
            Customers=("Customer ID", "count")
        )
    )

    fig = px.pie(
        summary,

        names="Customer Type",

        values="Customers",

        hole=0.55,

        title="New vs Returning Customers",
    )

    fig.update_traces(
        textposition="inside",

        textinfo="percent+label",
    )

    return customer_chart_layout(fig)

# ==========================================================
# NEW VS RETURNING CUSTOMER REVENUE
# ==========================================================

def new_vs_returning_revenue_chart(df):

    customer_orders = (
        df.groupby("Customer ID")
        .agg(
            Orders=("Order ID", "nunique"),
            Revenue=("Revenue", "sum"),
        )
        .reset_index()
    )

    customer_orders["Customer Type"] = (
        customer_orders["Orders"]
        .apply(
            lambda x:
            "New Customer"
            if x == 1
            else "Returning Customer"
        )
    )

    summary = (
        customer_orders
        .groupby(
            "Customer Type",
            as_index=False
        )
        .agg(
            Revenue=("Revenue", "sum")
        )
    )

    fig = px.bar(
        summary,

        x="Customer Type",

        y="Revenue",

        color="Customer Type",

        title="New vs Returning Customer Revenue",
    )

    return customer_chart_layout(fig)
# ==========================================================
# CUSTOMER DRILL-DOWN
# ==========================================================

def customer_drilldown(df, customer_name):

    customer_df = df[
        df["Customer Name"] == customer_name
    ].copy()

    if customer_df.empty:
        return None

    total_revenue = customer_df["Revenue"].sum()

    total_profit = customer_df["Profit"].sum()

    orders = customer_df["Order ID"].nunique()

    products = customer_df["Product Name"].nunique()

    regions = customer_df["Region"].nunique()

    margin = (
        total_profit / total_revenue * 100
        if total_revenue != 0
        else 0
    )

    return {
        "Revenue": total_revenue,
        "Profit": total_profit,
        "Orders": orders,
        "Products": products,
        "Regions": regions,
        "Margin": margin,
    }


# ==========================================================
# HIGH-VALUE CUSTOMERS
# ==========================================================

def high_value_customers(df, limit=20):

    customer_summary = (
        df.groupby(
            "Customer Name",
            as_index=False
        )
        .agg(
            Orders=("Order ID", "nunique"),
            Revenue=("Revenue", "sum"),
            Profit=("Profit", "sum"),
        )
        .sort_values(
            "Revenue",
            ascending=False
        )
        .head(limit)
        .reset_index(drop=True)
    )

    customer_summary.insert(
        0,
        "Rank",
        range(
            1,
            len(customer_summary) + 1
        )
    )

    return customer_summary


# ==========================================================
# AT-RISK CUSTOMERS
# ==========================================================

def at_risk_customers(df, limit=20):

    customer_summary = (
        df.groupby(
            "Customer Name",
            as_index=False
        )
        .agg(
            Orders=("Order ID", "nunique"),
            Revenue=("Revenue", "sum"),
            Profit=("Profit", "sum"),
        )
    )

    customer_summary["Profit Margin"] = (
        customer_summary["Profit"]
        / customer_summary["Revenue"]
        * 100
    )

    # Customers with only one order are treated as
    # potential retention opportunities.

    at_risk = (
        customer_summary[
            customer_summary["Orders"] == 1
        ]
        .sort_values(
            "Revenue",
            ascending=False
        )
        .head(limit)
        .reset_index(drop=True)
    )

    at_risk.insert(
        0,
        "Rank",
        range(
            1,
            len(at_risk) + 1
        )
    )

    return at_risk
