import pandas as pd


# ==========================================================
# PRODUCT KPI ENGINE
# ==========================================================

def total_products(df):
    """Return the number of unique products."""

    return df["Product ID"].nunique()


def total_product_revenue(df):
    """Return total revenue generated by products."""

    return df["Revenue"].sum()


def total_product_profit(df):
    """Return total profit generated by products."""

    return df["Profit"].sum()


def average_product_revenue(df):
    """Return average revenue per unique product."""

    products = df["Product ID"].nunique()

    if products == 0:
        return 0

    return df["Revenue"].sum() / products


def average_product_profit(df):
    """Return average profit per unique product."""

    products = df["Product ID"].nunique()

    if products == 0:
        return 0

    return df["Profit"].sum() / products


def product_profit_margin(df):
    """Return overall product profit margin."""

    revenue = df["Revenue"].sum()

    if revenue == 0:
        return 0

    return (
        df["Profit"].sum()
        / revenue
        * 100
    )


def total_units_sold(df):
    """Return total quantity of products sold."""

    return df["Quantity"].sum()


# ==========================================================
# PRODUCT PERFORMANCE
# ==========================================================

def top_products_by_revenue(df, limit=20):
    """Return top products ranked by revenue."""

    products = (
        df.groupby(
            ["Product ID", "Product Name"],
            as_index=False
        )
        .agg(
            Units=("Quantity", "sum"),
            Orders=("Order ID", "nunique"),
            Revenue=("Revenue", "sum"),
            Profit=("Profit", "sum"),
        )
        .sort_values(
            "Revenue",
            ascending=False
        )
        .head(limit)
        .reset_index(drop=True)
    )

    products.insert(
        0,
        "Rank",
        range(
            1,
            len(products) + 1
        )
    )

    return products


def top_products_by_profit(df, limit=20):
    """Return top products ranked by profit."""

    products = (
        df.groupby(
            ["Product ID", "Product Name"],
            as_index=False
        )
        .agg(
            Units=("Quantity", "sum"),
            Orders=("Order ID", "nunique"),
            Revenue=("Revenue", "sum"),
            Profit=("Profit", "sum"),
        )
        .sort_values(
            "Profit",
            ascending=False
        )
        .head(limit)
        .reset_index(drop=True)
    )

    products.insert(
        0,
        "Rank",
        range(
            1,
            len(products) + 1
        )
    )

    return products


# ==========================================================
# CATEGORY ANALYSIS
# ==========================================================

def product_category_summary(df):
    """Return product performance by category."""

    return (
        df.groupby(
            "Category",
            as_index=False
        )
        .agg(
            Products=("Product ID", "nunique"),
            Units=("Quantity", "sum"),
            Orders=("Order ID", "nunique"),
            Revenue=("Revenue", "sum"),
            Profit=("Profit", "sum"),
        )
        .sort_values(
            "Revenue",
            ascending=False
        )
        .reset_index(drop=True)
    )


# ==========================================================
# SUBCATEGORY ANALYSIS
# ==========================================================

def product_subcategory_summary(df):
    """Return product performance by subcategory."""

    return (
        df.groupby(
            "Subcategory",
            as_index=False
        )
        .agg(
            Products=("Product ID", "nunique"),
            Units=("Quantity", "sum"),
            Revenue=("Revenue", "sum"),
            Profit=("Profit", "sum"),
        )
        .sort_values(
            "Revenue",
            ascending=False
        )
        .reset_index(drop=True)
    )


# ==========================================================
# PRODUCT PROFITABILITY
# ==========================================================

def product_profitability(df, limit=20):
    """Return products ranked by profit margin."""

    summary = (
        df.groupby(
            ["Product ID", "Product Name"],
            as_index=False
        )
        .agg(
            Revenue=("Revenue", "sum"),
            Profit=("Profit", "sum"),
            Units=("Quantity", "sum"),
        )
    )

    summary["Profit Margin"] = (
        summary["Profit"]
        / summary["Revenue"]
        * 100
    )

    summary = (
        summary[
            summary["Revenue"] > 0
        ]
        .sort_values(
            "Profit Margin",
            ascending=False
        )
        .head(limit)
        .reset_index(drop=True)
    )

    summary.insert(
        0,
        "Rank",
        range(
            1,
            len(summary) + 1
        )
    )

    return summary


# ==========================================================
# PRODUCT DRILL-DOWN
# ==========================================================

def product_drilldown(df, product_name):
    """Return detailed performance for a selected product."""

    product_df = df[
        df["Product Name"] == product_name
    ].copy()

    if product_df.empty:
        return None

    revenue = product_df["Revenue"].sum()

    profit = product_df["Profit"].sum()

    units = product_df["Quantity"].sum()

    orders = product_df["Order ID"].nunique()

    customers = product_df["Customer ID"].nunique()

    regions = product_df["Region"].nunique()

    margin = (
        profit / revenue * 100
        if revenue != 0
        else 0
    )

    return {
        "Revenue": revenue,
        "Profit": profit,
        "Units": units,
        "Orders": orders,
        "Customers": customers,
        "Regions": regions,
        "Margin": margin,
    }


# ==========================================================
# PRODUCT RANKING
# ==========================================================

def product_ranking(df):
    """Return all products ranked by revenue."""

    ranking = (
        df.groupby(
            ["Product ID", "Product Name"],
            as_index=False
        )
        .agg(
            Units=("Quantity", "sum"),
            Orders=("Order ID", "nunique"),
            Customers=("Customer ID", "nunique"),
            Revenue=("Revenue", "sum"),
            Profit=("Profit", "sum"),
        )
        .sort_values(
            "Revenue",
            ascending=False
        )
        .reset_index(drop=True)
    )

    ranking.insert(
        0,
        "Rank",
        range(
            1,
            len(ranking) + 1
        )
    )

    ranking["Profit Margin"] = (
        ranking["Profit"]
        / ranking["Revenue"]
        * 100
    )

    return ranking

